version: '3.8'

services:
  backend:
    build:
      context: ./backend       # Dockerfileがあるディレクトリを指定
      dockerfile: Dockerfile   # backendディレクトリ内のDockerfileを指定
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./backend/.env       # backendディレクトリ内の.envを指定
    command: ["/server"]